apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-inference
  labels:
    app: mnist-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-inference
  template:
    metadata:
      labels:
        app: mnist-inference
    spec:
      containers:
        - name: mnist-inference
          image: us-east1-docker.pkg.dev/coms6998-spring2025/mnist-repo/mnist-inference:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: model-storage
              mountPath: /models
              readOnly: true
          livenessProbe:
            httpGet:
              path: /status
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage-pvc